### ISSUE TITLE
Unexpected Token Error: ResponseEntity argument 

### ISSUE THREAD

**Issue by WannabeFarmer** [210419-USF-BSN-Java/Canoe-Back-End#2]
As much an FYI as a bug fix request: 
Client expects JSON and throws unexpected token error when string is passed in non-JSON format. 

From  UserController.java
``` java
// throws error
return new ResponseEntity<String>("Email already exists", HttpStatus.BAD_REQUEST);

// works. does not throw error
return new ResponseEntity<String>("{\"message\":  \" Email already exists\"}", HttpStatus.BAD_REQUEST);

```

**Comment by devaraj1234** [comment]
I have set up the email as unique. That's why it throwing a bad request. That is not an error.

**Comment by devaraj1234** [comment]
done
